CenterForOpenScience/developer.osf.io

swagger-spec/preprint_providers/definition.yaml, swagger-spec/preprint_providers/detail.yaml, swagger-spec/preprint_providers/licenses_list.yaml, swagger-spec/preprint_providers/list.yaml, swagger-spec/preprint_providers/preprints_list.yaml, swagger-spec/preprint_providers/taxonomies_list.yaml, swagger-spec/swagger.yaml
Add docs for https://openscience.atlassian.net/browse/IN-150
* Add deprecation note for `preprint_providers`
* Update urls to `providers/preprints`
* Remove previously deprecated fields that are no longer present:
```
header_text
banner_path
logo_path
email_contact
social_twitter
social_facebook
social_instagram
subjects_acceptable
```
=> [IN-227][DeveloperDocs] Deprecate preprint_providers

swagger-spec/identifiers/definition.yaml, swagger-spec/identifiers/detail.yaml, swagger-spec/identifiers/list.yaml, swagger-spec/logs/actions.yaml, swagger-spec/logs/definition.yaml, swagger-spec/nodes/definition.yaml, swagger-spec/nodes/identifiers_list.yaml, swagger-spec/registrations/definition.yaml, swagger-spec/registrations/identifiers_list.yaml, swagger-spec/swagger.yaml
We don't support arks anymore, so lets remove them from the docs.
- just textual changes.
https://openscience.atlassian.net/projects/PLAT/issues/PLAT-856
=> [PLAT-856] Remove references to ARKs from API docs

swagger-spec/nodes/citation_detail.yaml, swagger-spec/nodes/citation_detail_definition.yaml, swagger-spec/registrations/style_detail.yaml
Citations for projects need to be consistent with our branding, so let's update project citations to say "OSF" instead of "Open Science Framework" as the publisher.
https://openscience.atlassian.net/browse/PLAT-804
=> Update citation detail to be consistent with branding: Open Science Framework > OSF

swagger-spec/nodes/node_settings_definition.yaml, swagger-spec/nodes/node_settings_detail.yaml, swagger-spec/swagger.yaml
Add documentation for NodeSettings API v2 endpoints.
Related OSF PR: https://github.com/CenterForOpenScience/osf.io/pull/8536
Related ticket: http://openscience.atlassian.net/browse/PLAT-924
=> Add documentation for node settings GET and PATCH endpoints [PLAT-924]

swagger-spec/external_identities/external_identities_detail.yaml, swagger-spec/swagger.yaml, swagger-spec/users/detail.yaml, swagger-spec/users/external_identities_detail.yaml, swagger-spec/users/external_identities_list.yaml
We have https://github.com/CenterForOpenScience/osf.io/pull/8540, so we need to document it!
- Simple textual changes
- Rogue typo
https://openscience.atlassian.net/projects/PLAT/issues/PLAT-931
=> [PLAT-931] Add External Identities endpoints to docs

swagger-spec/nodes/files_list.yaml, swagger-spec/registrations/files_list.yaml
Filtering file on nodes was redundant  and bugged, so we removed it. This fix changes the docs to account for the change.
- Simple textual changes
None that I know of.
https://openscience.atlassian.net/projects/PLAT/issues/PLAT-990
=> [PLAT-990] Remove node from list of filterable attributes

swagger-spec/swagger.yaml, swagger-spec/users/settings_detail.yaml
User settings docs, specifically two-factor auth fields
Related PR https://github.com/CenterForOpenScience/osf.io/pull/8565
Adds GET/PATCH user settings docs
https://openscience.atlassian.net/browse/PLAT-963
=> Feature/User Settings Docs [PLAT-963]

swagger-spec/nodes/registrations_list.yaml, swagger-spec/registrations/definition.yaml
Show people how to register a limited selection of a node's children
- simple doc changes
Might be nice to have a picture detailing the whole, no grandchildren without children thing, but my image design skill is not great.
https://openscience.atlassian.net/projects/PLAT/issues/PLAT-836
https://github.com/CenterForOpenScience/osf.io/pull/8399
=> [PLAT-836] add docs for partial registrations.

swagger-spec/swagger.yaml
Update the dev docs to reference api.test.osf.io instead of the outdated test-api.osf.io site
https://openscience.atlassian.net/browse/PLAT-1252
=> Update test api url in dev docs [PLAT-1252]

swagger-spec/logs/actions.yaml, swagger-spec/nodes/definition.yaml, swagger-spec/nodes/draft_registration_definition.yaml, swagger-spec/nodes/draft_registration_detail.yaml, swagger-spec/nodes/draft_registration_detail_definition.yaml, swagger-spec/nodes/draft_registrations_list.yaml, swagger-spec/nodes/preprints_list.yaml, swagger-spec/preprints/definition.yaml, swagger-spec/preprints/detail.yaml, swagger-spec/preprints/list.yaml, swagger-spec/users/preprints_list.yaml
Update docs to reflect preprints' removal of the dependency on a node. While I'm here, adding to docs for Node Draft Registrations - registration schema is set via relationships instead of attributes.
- Definition of a preprint updated, preprint serializer has many more fields that were previously stored on the node
- Preprint Create/Update modified to reflect changes in the process, WB file requests also detailed
- Preprint List, User Preprints, Node Preprints definitions modified
- Preprint node relationship, preprint attribute modified to reflect this is whether projects contain supplemental material for a preprint, rather than this was the node created for a preprint.
- Draft Registration creation information updated, as well as draft registration required fields …
=> NPD docs + Draft Registration docs correction [PLAT-555] [PLAT-1001]

swagger-spec/nodes/definition.yaml
Add an example of adding tags when creating a node.
Since tags are a normal attribute and they are already included in the update payload example, I didn't add any more tag-specific information in any descriptions as it will be the same for any attribute on any object.
https://openscience.atlassian.net/browse/PLAT-591
=> Add tags to node request sample [PLAT-591]

swagger-spec/nodes/wikis_list.yaml, swagger-spec/wikis/definition.yaml, swagger-spec/wikis/versions_list.yaml
We have pretty thorough API v2 wiki docs, but because there are different endpoints involved (node endpoints and wiki endpoints), it can be difficult to find the pieces necessary.
- Remove wiki relationship links as `required` fields in request - this isn't correct.
- Link the different sections of wiki docs together
=> Feature/Improve Wiki Docs [PLAT-1306]

swagger-spec/identifiers/definition.yaml, swagger-spec/nodes/identifiers_list.yaml, swagger-spec/nodes/registrations_list.yaml, swagger-spec/registrations/definition.yaml, swagger-spec/registrations/detail.yaml, swagger-spec/registrations/identifiers_list.yaml
Add dev docs for editable registration fields and minting DOI's for nodes and registrations.
=> Feature/APIv2 Editable Registration Fields and Minting DOI docs [EMB-567][EMB-570]

swagger-spec/search/components.yaml, swagger-spec/search/components_definition.yaml, swagger-spec/search/definition.yaml, swagger-spec/search/files.yaml, swagger-spec/search/files_definition.yaml, swagger-spec/search/institutions.yaml, swagger-spec/search/institutions_definition.yaml, swagger-spec/search/projects.yaml, swagger-spec/search/projects_definition.yaml, swagger-spec/search/registrations.yaml, swagger-spec/search/registrations_definition.yaml, swagger-spec/search/search.yaml, swagger-spec/search/users.yaml, swagger-spec/search/users_definition.yaml, swagger-spec/swagger.yaml
To document the existence of our search!
Add docs for general search endpoint: `/v2/search/` and the filtered endpoints `/v2/search/files` etc. Also adds some search syntax info.
None that I know of.
https://openscience.atlassian.net/browse/ENG-357
=> [ENG-357] Document /search/ API endpoints 

swagger-spec/swagger.yaml
- Add the latest three API versions to the changelog 2.14-2.16.  (2.16 unmerged, but will go out as part of editable registrations)
https://github.com/CenterForOpenScience/osf.io/pull/8948
https://openscience.atlassian.net/browse/ENG-161
=> Feature/Update Changelog

swagger-spec/users/settings_detail.yaml
Add paragraph in `return` section detailing when `secret` will be included in response from `PUT` or `PATCH` requests.
Ticket: https://openscience.atlassian.net/browse/PLAT-1280
=> Add details about returning a secret for enabling two factor authentication

swagger-spec/files/version_definition.yaml, swagger-spec/files/version_detail.yaml, swagger-spec/files/versions_list.yaml, swagger-spec/nodes/addon_detail.yaml, swagger-spec/nodes/addons_list.yaml, swagger-spec/nodes/draft_registration_definition.yaml, swagger-spec/nodes/draft_registration_detail.yaml, swagger-spec/nodes/draft_registration_detail_definition.yaml, swagger-spec/nodes/draft_registrations_list.yaml, swagger-spec/nodes/node_addon_definition.yaml, swagger-spec/swagger.yaml, swagger-spec/users/addon_account_definition.yaml, swagger-spec/users/addon_account_detail.yaml, swagger-spec/users/addon_accounts_list.yaml, swagger-spec/users/addon_detail.yaml, swagger-spec/users/addons_list.yaml, swagger-spec/users/user_addon_definition.yaml
API Version 2.15 deprecates snake_case for all types and replaces with kebab-case. Also added documentation for API version 2.14 which was missing and deprecated the logo_path for institutions..
=> Modifying documentation for API Version 2.15

swagger-spec/collections/collected_metadata_subjects.yaml, swagger-spec/draft_registrations/draft_registration_definition.yaml, swagger-spec/draft_registrations/draft_registration_detail.yaml, swagger-spec/draft_registrations/draft_registrations_contributors_detail.yaml, swagger-spec/draft_registrations/draft_registrations_contributors_list.yaml, swagger-spec/draft_registrations/draft_registrations_institutions_list.yaml, swagger-spec/draft_registrations/draft_registrations_list.yaml, swagger-spec/draft_registrations/draft_registrations_subjects_list.yaml, swagger-spec/nodes/contributor_definition.yaml, swagger-spec/nodes/draft_registration_detail.yaml, swagger-spec/nodes/draft_registrations_list.yaml, swagger-spec/preprint_providers/licenses_list.yaml, swagger-spec/subjects/subject_definition.yaml, swagger-spec/swagger.yaml
Add no-project registrations and PATHCHing, contributor adding and other modern Draft Registration behavior
```yaml
##########################
##########################
/draft_registrations/:
$ref: 'draft_registrations/draft_registrations_list.yaml'
/draft_registrations/{draft_id}/:
$ref: 'draft_registrations/draft_registration_detail.yaml'
/draft_registrations/{draft_id}/contributors/:
$ref: 'draft_registrations/draft_registrations_contributors_list.yaml'
/draft_registrations/{draft_id}/contributors/{user_id}/:
$ref: 'draft_registrations/draft_registrations_contributors_detail.yaml'
/draft_registrations/{draft_id}/institutions/:
$ref: 'draft_registrations/draft_registrations_institutions_list.yaml'
/draft_registrations/{draft_id}/subjects/:
$ref: …
```
=> [ENG-2480] Add no-project registrations 

swagger-spec/swagger.yaml
-   Ticket: n/a
-   Feature flag: feature/metadata-button-file-detail from upstream/guid-metadata
The purpose of these changes is to correct spelling in the testing section and to match casing from 'osf' to 'OSF' in the v2 API documentation.
The spelling has been corrected and 'osf' capitalized to 'OSF'.
=> [ENG-XXXX] Correct spelling for testing content, all cap osf

swagger-spec/swagger.yaml
[ENG-5090](https://openscience.atlassian.net/browse/ENG-5090) (Part of [ENG-2996])(https://openscience.atlassian.net/browse/ENG-2996)
* Update OAuth link to the new guide
* Remove reference to the deprecated test app
* Fix links to the developer app page
[ENG-5090]: https://openscience.atlassian.net/browse/ENG-5090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG-2996]: https://openscience.atlassian.net/browse/ENG-2996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ENG-2996] [ENG-5090] Update token and oauth guide

swagger-spec/preprints/definition.yaml, swagger-spec/preprints/detail.yaml, swagger-spec/preprints/versioned_preprints_list.yaml, swagger-spec/swagger.yaml
Add versioned preprints endpoints
https://openscience.atlassian.net/browse/ENG-6782
=> [ENG-6782] Update preprint API documents
