swagger-spec/nodes/wikis_list.yaml
swagger-spec/swagger.yaml
swagger-spec/wikis/content.yaml
swagger-spec/wikis/definition.yaml
swagger-spec/wikis/detail.yaml
swagger-spec/wikis/version_content.yaml
swagger-spec/wikis/version_definition.yaml
swagger-spec/wikis/version_detail.yaml
swagger-spec/wikis/versions_list.yaml

* Add wiki version information to docs. 
* Add docs for writeable wiki operations.
* Create
* Rename
* Update content/create new version
* Delete
Replaces #7

[PLAT-469] [PLAT-543] Wiki Documentation

---

swagger-spec/swagger.yaml

* Add documentation for versions 2.5, 2.6, and 2.7 
* Move the changelog to it's own section.

Update changelog 

---

swagger-spec/nodes/children_list.yaml

A user in the attached wanted to know what response they'd get if the created a child node. This will let them know.
- Simple textual changes
https://openscience.atlassian.net/browse/PLAT-1027

[PLAT-1027] Add docs for creating child nodes

---

swagger-spec/users/definition.yaml

Update social fields info on user API docs
https://openscience.atlassian.net/browse/PLAT-925

Add social fields documentation for updating and retrieving for a user [PLAT-925]

---

swagger-spec/swagger.yaml

Add docs for related_counts.
- Simple textual changes
https://openscience.atlassian.net/projects/PLAT/issues/PLAT-846

[PLAT-846] Add docs for related counts

---

swagger-spec/institutions/definition.yaml
swagger-spec/institutions/detail.yaml

https://openscience.atlassian.net/browse/PLAT-1211

Add html link for institutions to docs

---

swagger-spec/metaschemas/registration_metaschema_list.yaml

To document how you can filter registration metaschemas now
Minor textual changes.

[PLAT-1177] Add metaschema filtering to docs

---

swagger-spec/nodes/node_settings_detail.yaml
swagger-spec/swagger.yaml
swagger-spec/users/external_identities_detail.yaml
swagger-spec/users/settings_detail.yaml

- Changelog now up to date with version 2.11
- Fix stricter build errors

Bring changelog up to date/fix small linting things

---

swagger-spec/institutions/definition.yaml
swagger-spec/institutions/detail.yaml
swagger-spec/institutions/list.yaml

To add the new institution's assets object to the docs.
- Removed `logo_path` from the docs
- Added `assets/logo_path` and `assets/logo_rounded`
N/A

Add institution assets to api docs

---

swagger-spec/nodes/linked_nodes_relationships.yaml
swagger-spec/swagger.yaml

Dev docs PR for https://github.com/CenterForOpenScience/osf.io/pull/8917
Also includes changelog update for https://github.com/CenterForOpenScience/osf.io/pull/8814

Update relationships types

---

swagger-spec/registrations/definition.yaml
swagger-spec/registrations/detail.yaml

Add docs with the payload for initiating a withdrawal of a registration
https://openscience.atlassian.net/browse/PLAT-1333

Feature/Withdraw Registration Docs [PLAT-1333]

---

swagger-spec/users/definition.yaml

Docs for https://github.com/CenterForOpenScience/osf.io/pull/8960

Feature/Add user default region to docs.

---

swagger-spec/files/definition.yaml
swagger-spec/files/detail.yaml
swagger-spec/files/version_definition.yaml
swagger-spec/files/version_detail.yaml
swagger-spec/files/versions_list.yaml

Adds docs for file/fileversion render, html, and download links.
https://openscience.atlassian.net/browse/PLAT-1173

Feature/Render Links [PLAT-1173]

---

swagger-spec/groups/definition.yaml
swagger-spec/groups/detail.yaml
swagger-spec/groups/group_member_definition.yaml
swagger-spec/groups/list.yaml
swagger-spec/groups/member_detail.yaml
swagger-spec/groups/members_list.yaml
swagger-spec/nodes/definition.yaml
swagger-spec/nodes/detail.yaml
swagger-spec/nodes/groups_detail.yaml
swagger-spec/nodes/groups_list.yaml
swagger-spec/nodes/node_group_definition.yaml
swagger-spec/swagger.yaml
swagger-spec/users/definition.yaml
swagger-spec/users/groups_list.yaml

Document Groups API
- GET GroupsList `/v2/groups/`
- POST GroupsList `/v2/groups/`
- GET GroupsDetail `/v2/groups/<group_id>`
- PATCH GroupsDetail `/v2/groups/<group_id>`
- DELETE GroupsDetail `/v2/groups/<group_id>`
- GET GroupMembersList `/v2/groups/<group_id>/members/`
- POST GroupMembersList `/v2/groups/<group_id>members/`
- GET GroupMemberDetail `/v2/groups/<group_id>/members/<user_id>/`
- PATCH GroupMemberDetail `/v2/groups/<group_id>/members/<user_id>/`
- DELETE GroupMemberDetail `/v2/groups/<group_id>/members/user_id/`
- GET NodeGroupsList `v2/nodes/<node_id>/groups/`
- POST NodeGroupsList  `v2/nodes/<node_id>/groups/`
- GET NodeGroupDetail  `v2/nodes/<node_id>/groups/<group_id>/`
- PATCH NodeGroupDetail `v2/nodes/<node_id>/groups/<group_id>/`
- DELETE NodeGroupDetail …

Feature/Groups API Documentation [PLAT-1183][PLAT-1184][PLAT-1192]

---

swagger-spec/collections/collected_metadata_detail.yaml
swagger-spec/collections/collected_metadata_list.yaml
swagger-spec/collections/collected_metadata_subjects.yaml
swagger-spec/collections/collected_metadata_subjects_relationships.yaml
swagger-spec/collections/detail.yaml

Clean-up docs syntax so it will deploy.
https://openscience.atlassian.net/browse/ENG-2695

[ENG-2695] syntax clean-up using swagger-cli

---

swagger-spec/preprints/definition.yaml
swagger-spec/preprints/detail.yaml

Add biblographic contribs to preprint docs
https://openscience.atlassian.net/browse/ENG-1993

[ENG-1993] Update dev docs to include preprint bib contribs

---

swagger-spec/collections/collected_metadata_subjects.yaml
swagger-spec/nodes/contributor_definition.yaml
swagger-spec/preprints/bibliographic_contributors_list.yaml
swagger-spec/preprints/contributor_definition.yaml
swagger-spec/preprints/contributor_detail.yaml
swagger-spec/preprints/contributors_list.yaml
swagger-spec/preprints/definition.yaml
swagger-spec/swagger.yaml

Add info about a preprint's bibliographic contributors
https://openscience.atlassian.net/browse/ENG-1993

[ENG-1993] Add Info for preprint's bibliographic contributors

---

swagger-spec/collection_provider/definition.yaml
swagger-spec/collection_provider/detail.yaml
swagger-spec/collection_provider/licenses.yaml
swagger-spec/collection_provider/list.yaml
swagger-spec/collection_provider/moderators_detail.yaml
swagger-spec/collection_provider/moderators_list.yaml
swagger-spec/collection_provider/subjects.yaml
swagger-spec/collection_provider/subjects_highlighted.yaml
swagger-spec/collection_provider/submissions.yaml
swagger-spec/collection_submission_actions/definition.yaml
swagger-spec/collection_submission_actions/detail.yaml
swagger-spec/collection_submission_actions/list.yaml
swagger-spec/collection_submissions/list.yaml
swagger-spec/swagger.yaml

Add more info of Collections Providers and Collection Submissions.
[WIP]
https://openscience.atlassian.net/browse/ENG-4242

[ENG-4242] Add collections moderation related documentation

---

swagger-spec/institutions/definition.yaml
swagger-spec/institutions/detail.yaml
swagger-spec/preprints/definition.yaml
swagger-spec/preprints/detail.yaml
swagger-spec/preprints/institutions_list.yaml
swagger-spec/preprints/institutions_relationship_list.yaml
swagger-spec/preprints/list.yaml
swagger-spec/swagger.yaml

To update Preprint and Institution model documents and show the addition of the new endpoints allow institutional affiliations for Preprints. 
- Add many new attributes and relationships to the existing Preprint and Institution models
- adds new file detailing institutional list endpoint  with GET relationship
- adds new file detailing institutional relationship list endpoint  with GET and PUT relationship
https://openscience.atlassian.net/browse/ENG-5891

[ENG-5891] 1.2.7 BE: Update API documentation (developer.osf.io)

---

swagger-spec/users/detail.yaml

FIx issues with updating social and employment info
- improvements to doc language showing example
None.

improve social, education, employment updating info
